from apps.hard_skill.models import UnknownHardSkill

HARD_SKILL_MAPPING = {
    ".net": ".NET",
    ".net core": ".NET",
    ".net framework": ".NET",
    "1c": "1С",
    "1с-битрикс": "1С-Битрикс",
    "1c-битрикс": "1С-Битрикс",
    "asp net": "ASP.NET",
    "aspnet": "ASP.NET",
    "asp.net": "ASP.NET",
    "angular": "Angular",
    "angular js": "Angular",
    "angular.js": "Angular",
    "ansible": "Ansible",
    "assembly": "Assembly",
    "aws": "AWS",
    "babel": "Babel",
    "bootstrap": "Bootstrap",
    "bitbucket": "BitBucket",
    "битрикс24": "Битрикс24",
    "битрикс 24": "Битрикс24",
    "bitrix24": "Битрикс24",
    "bitrix 24": "Битрикс24",
    "css": "CSS",
    "css3": "CSS",
    "css 3": "CSS",
    "scss": "SASS",
    "sass": "SASS",
    "c": "C",
    "c#": "C#",
    "c++": "C++",
    "ci/cd": "CI/CD",
    "celery": "Celery",
    "confluence": "Confluence",
    "clickhouse": "ClickHouse",
    "cucumber": "Cucumber",
    "delphi": "Delphi",
    "dart": "Dart",
    "devops": "DevOps",
    "django": "Django",
    "django rest": "Django REST Framework",
    "django framework": "Django REST Framework",
    "django rest framework": "Django REST Framework",
    "rest framework": "Django REST Framework",
    "docker": "Docker",
    "docker compose": "Docker Compose",
    "docker-compose": "Docker Compose",
    "express": "Express",
    "erlang": "Erlang",
    "emberjs": "Ember.js",
    "ember js": "Ember.js",
    "ember.js": "Ember.js",
    "electron": "Electron",
    "elasticsearch": "Elasticsearch",
    "elastic search": "Elasticsearch",
    "elixir": "Elixir",
    "f#": "F#",
    "fastapi": "FastAPI",
    "fast api": "FastAPI",
    "figma": "Figma",
    "flask": "Flask",
    "flutter": "Flutter",
    "git": "Git",
    "grails": "Grails",
    "github": "GitHub",
    "gitlab": "GitLab",
    "go": "Go",
    "golang": "Go",
    "go lang": "Go",
    "graphql": "GraphQL",
    "grafana": "Grafana",
    "html": "HTML",
    "html5": "HTML",
    "html 5": "HTML",
    "haskell": "Haskell",
    "jquery": "JQuery",
    "js": "JavaScript",
    "javascript": "JavaScript",
    "java script": "JavaScript",
    "java": "Java",
    "jenkins": "Jenkins",
    "jira": "Jira",
    "jest": "Jest",
    "kafka": "Kafka",
    "kotlin": "Kotlin",
    "kubernetes": "Kubernetes",
    "k8s": "Kubernetes",
    "laravel": "Laravel",
    "linux": "Linux",
    "lua": "Lua",
    "less": "Less",
    "mongodb": "MongoDB",
    "meteor": "Meteor",
    "mysql": "MySQL",
    "nginx": "Nginx",
    "node.js": "Node.js",
    "node js": "Node.js",
    "nextjs": "Next.js",
    "next.js": "Next.js",
    "next js": "Next.js",
    "nuxtjs": "Nuxt.js",
    "nuxt.js": "Nuxt.js",
    "nuxt js": "Nuxt.js",
    "nestjs": "NestJS",
    "nest.js": "NestJS",
    "nest js": "NestJS",
    "nosql": "NoSQL",
    "no sql": "NoSQL",
    "oop": "ООП",
    "ооп": "ООП",
    "oracle": "Oracle",
    "php": "PHP",
    "postgresql": "PostgreSQL",
    "postgres": "PostgreSQL",
    "postgre sql": "PostgreSQL",
    "postgres sql": "PostgreSQL",
    "postgresql sql": "PostgreSQL",
    "psql": "PostgreSQL",
    "python": "Python",
    "python3": "Python",
    "python 3": "Python",
    "pytorch": "PyTorch",
    "perl": "Perl",
    "pandas": "Pandas",
    "postman": "Postman",
    "rest": "REST API",
    "restapi": "REST API",
    "rest api": "REST API",
    "restful": "REST API",
    "restful api": "REST API",
    "rest-api": "REST API",
    "rabbit": "RabbitMQ",
    "rabbit mq": "RabbitMQ",
    "rabbitmq": "RabbitMQ",
    "react": "React",
    "react.js": "React",
    "react js": "React",
    "reactnative": "React Native",
    "react native": "React Native",
    "redis": "Redis",
    "redux": "Redux",
    "redux toolkit": "Redux Toolkit",
    "redux-toolkit": "Redux Toolkit",
    "react testing library": "React Testing Library",
    "react-query": "React Query",
    "react query": "React Query",
    "rtk-query": "RTK Query",
    "rtk query": "RTK Query",
    "ruby": "Ruby",
    "rust": "Rust",
    "svelte": "Svelte",
    "seo": "SEO",
    "seo оптимизация": "SEO",
    "seo-оптимизация": "SEO",
    "sql": "SQL",
    "sqlalchemy": "SQLAlchemy",
    "sql alchemy": "SQLAlchemy",
    "spring": "Spring",
    "spring boot": "Spring",
    "spring framework": "Spring",
    "swift": "Swift",
    "tcp/ip": "TCP/IP",
    "tailwind": "Tailwind",
    "tailwindcss": "Tailwind",
    "tailwind css": "Tailwind",
    "ts": "TypeScript",
    "typescript": "TypeScript",
    "type script": "TypeScript",
    "tensorflow": "TensorFlow",
    "vue": "Vue",
    "vue3": "Vue",
    "vue js": "Vue",
    "vuejs": "Vue",
    "vue.js": "Vue",
    "webpack": "Webpack",
    "websocket": "WebSocket",
}


def normalize_hard_skill(skill: str):
    normalized_skill = HARD_SKILL_MAPPING.get(skill.lower())
    if normalized_skill:
        return normalized_skill
    else:
        hard_skill, _ = UnknownHardSkill.objects.get_or_create(name=skill)
        return None
