server {
    listen 80;
    server_name syncit.space;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /api {
        try_files $uri @proxy_api;
    }

    location /admin {
        try_files $uri @proxy_api;
    }

    location = /robots.txt {
        try_files $uri @proxy_api;
    }

    location @proxy_api {
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_pass http://django:8000;
    }

    location /static {
        alias /project/backend/django/static;
        expires 1d;
        add_header Cache-Control "public";
    }
}
