name: syncit

services:
  frontend:
    build:
      context: ./frontend
      target: ${BUILD_TARGET}
    volumes:
      - ./frontend:/project/frontend
      - /project/frontend/node_modules
      - frontend_dist:/project/frontend/dist
      - static_volume:/project/backend/django/django_static
    ports:
      - "80:80"
      - "3000:3000"
    networks:
      - app-network

  django:
    build:
      context: ./backend/django
      target: ${BUILD_TARGET}
    volumes:
      - ./backend/django:/project/backend/django
      - static_volume:/project/backend/django/django_static/
    ports:
      - "8000:8000"
    env_file:
      - .env
    healthcheck:
      test: "curl -f http://localhost:8000/health-check/"
      interval: 10s
      timeout: 5s
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  go:
    build:
      context: ./backend/go
      target: ${BUILD_TARGET}
    volumes:
      - ./backend/go:/project/backend/go
    ports:
      - "9000:9000"
    env_file:
      - .env
    healthcheck:
      test: "curl -f http://localhost:9000/health-check"
      interval: 10s
      timeout: 5s
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:16.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    env_file:
      - .env
    healthcheck:
      test: "pg_isready -h ${POSTGRES_HOST} -p ${POSTGRES_PORT} -d ${POSTGRES_DB}"
      interval: 10s
      timeout: 5s
    networks:
      - app-network

  redis:
    image: redis:7.2.5-alpine
    hostname: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: "redis-cli ping"
      interval: 10s
      timeout: 5s
    networks:
      - app-network

  celery:
    build:
      context: ./backend/django
      target: ${BUILD_TARGET}
    command: celery -A core.celery.app worker -l ${CELERY_LOG_LEVEL}
    healthcheck:
      test: "celery -A core.celery.app inspect ping"
      interval: 10s
      timeout: 5s
    depends_on:
      - django
      - redis
    env_file:
      - .env
    networks:
      - app-network

  celery-beat:
    build:
      context: ./backend/django
      target: ${BUILD_TARGET}
    env_file:
      - .env
    command: celery -A core.celery.app beat -l ${CELERY_LOG_LEVEL}
    depends_on:
      - django
      - redis
    labels:
      telegram-notifier.monitor: false
    networks:
      - app-network

  flower:
    build:
      context: ./backend/django
      target: ${BUILD_TARGET}
    command: celery -A core.celery.app flower -l ${CELERY_LOG_LEVEL}
    env_file:
      - .env
    ports:
      - "5555:5555"
    labels:
      telegram-notifier.monitor: false
    networks:
      - app-network

  notifier:
    image: lorcas/docker-telegram-notifier
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - .env
    labels:
      telegram-notifier.monitor: false

  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    labels:
      telegram-notifier.monitor: false
    networks:
      - app-network


volumes:
  static_volume:
  frontend_dist:
  postgres_data:


networks:
  app-network:
    driver: bridge
