# Generated by Django 5.0.7 on 2024-07-23 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hard_skill', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unknownhardskill',
            options={'ordering': ('name',)},
        ),
    ]
