# Generated by Django 5.0.7 on 2024-07-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hard_skill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unknownhardskill',
            name='create_count',
            field=models.IntegerField(default=0),
        ),
    ]
