# Generated by Django 5.0.7 on 2024-07-29 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hard_skill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardskill',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='hard_skill.hardskill'),
        ),
    ]
