# Generated by Django 5.0.7 on 2024-07-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hard_skill', '0002_unknownhardskill_create_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unknownhardskill',
            options={'ordering': ('create_count',)},
        ),
        migrations.AlterField(
            model_name='unknownhardskill',
            name='create_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
