# Generated by Django 5.0.7 on 2024-07-26 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hard_skill', '0003_category_hardskill_parent_hardskill_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardskill',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hard_skill.category'),
        ),
        migrations.AlterField(
            model_name='hardskill',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hard_skill.hardskill'),
        ),
    ]
