# Generated by Django 5.0.7 on 2024-07-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hard_skill', '0004_alter_unknownhardskill_create_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unknownhardskill',
            name='create_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
