# Generated by Django 5.0.7 on 2024-07-26 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hard_skill', '0004_remove_hardskill_category_category_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardskill',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hard_skill.category'),
            preserve_default=False,
        ),
    ]
