# Generated by Django 5.0.7 on 2024-07-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hard_skill', '0005_alter_unknownhardskill_create_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unknownhardskill',
            name='create_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
