# Generated by Django 5.0.7 on 2024-07-26 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hard_skill', '0005_hardskill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardskill',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hard_skill.category'),
        ),
    ]
