# Generated by Django 5.0.7 on 2024-07-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hard_skill', '0006_alter_unknownhardskill_create_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unknownhardskill',
            options={'ordering': ('-create_count',)},
        ),
        migrations.AlterField(
            model_name='unknownhardskill',
            name='create_count',
            field=models.IntegerField(null=True),
        ),
    ]
