# Generated by Django 5.0.7 on 2024-07-28 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hard_skill', '0007_alter_unknownhardskill_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hardskill',
            name='unique_hardskill_name_parent',
        ),
        migrations.AlterUniqueTogether(
            name='hardskill',
            unique_together={('name', 'parent')},
        ),
    ]
