# Generated by Django 5.0.7 on 2024-07-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hard_skill', '0008_remove_category_parent_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ManyToManyField(blank=True, to='hard_skill.category'),
        ),
    ]
