# Generated by Django 5.0.7 on 2024-07-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hard_skill', '0010_remove_category_parent_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='hardskill',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='hardskill',
            options={},
        ),
        migrations.AddField(
            model_name='hardskill',
            name='selectable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='hardskill',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='hardskill',
            constraint=models.UniqueConstraint(fields=('name', 'parent'), name='unique_hardskill_name_parent'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
