# Generated by Django 5.0.6 on 2024-07-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0001_initial'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='professions',
            field=models.ManyToManyField(related_name='profiles', to='profession.profession'),
        ),
    ]
