# Generated by Django 5.0.7 on 2024-07-28 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='vacancies',
        ),
    ]
