# Generated by Django 5.0.7 on 2024-07-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0001_initial"),
        ("vacancy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="vacancies",
            field=models.ManyToManyField(related_name="profiles", to="vacancy.vacancy"),
        ),
    ]
