# Generated by Django 5.0.7 on 2024-07-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_profile_vacancies'),
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='vacancies',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='vacancy.vacancy'),
        ),
    ]
