# Generated by Django 5.0.7 on 2024-07-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
        ('hard_skill', '0007_alter_unknownhardskill_options_and_more'),
        ('profession', '0001_initial'),
        ('user_profile', '0002_remove_profile_vacancies'),
        ('work_format', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='grades',
            field=models.ManyToManyField(null=True, related_name='profiles', to='grade.grade'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hard_skills',
            field=models.ManyToManyField(null=True, related_name='profiles', to='hard_skill.hardskill'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='professions',
            field=models.ManyToManyField(null=True, related_name='profiles', to='profession.profession'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_formats',
            field=models.ManyToManyField(null=True, related_name='profiles', to='work_format.workformat'),
        ),
    ]
