# Generated by Django 5.0.6 on 2024-07-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_profile_grades'),
        ('work_format', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='work_formats',
            field=models.ManyToManyField(related_name='profiles', to='work_format.workformat'),
        ),
    ]
