# Generated by Django 5.0.7 on 2024-07-29 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_alter_uservacancy_suitability_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uservacancy',
            old_name='suitability_percentage',
            new_name='suitability',
        ),
    ]
