# Generated by Django 5.0.7 on 2024-07-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_uservacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedvacancy',
            name='name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parsedvacancy',
            name='url',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
