# Generated by Django 5.0.7 on 2024-07-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_parsedvacancy_name_parsedvacancy_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservacancy',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
