# Generated by Django 5.1.6 on 2025-02-24 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grade", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="grade",
            old_name="order",
            new_name="ordering",
        ),
    ]
