# Generated by Django 5.1.6 on 2025-02-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grade", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="grade",
            options={"ordering": ("order",)},
        ),
        migrations.AddField(
            model_name="grade",
            name="order",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
