# Generated by Django 5.1.6 on 2025-02-17 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grade", "0002_alter_grade_options_grade_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="grade",
            options={},
        ),
    ]
