# Generated by Django 5.1.6 on 2025-02-17 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profession", "0002_alter_profession_options_profession_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profession",
            options={},
        ),
    ]
