# Generated by Django 5.1.6 on 2025-02-23 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("grade", "0001_initial"),
        ("profession", "0001_initial"),
        ("skill", "0001_initial"),
        ("work_format", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "grades",
                    models.ManyToManyField(
                        blank=True, related_name="profiles", to="grade.grade"
                    ),
                ),
                (
                    "professions",
                    models.ManyToManyField(
                        blank=True, related_name="profiles", to="profession.profession"
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        blank=True, related_name="profiles", to="skill.skill"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_formats",
                    models.ManyToManyField(
                        blank=True, related_name="profiles", to="work_format.workformat"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user"], name="user_profil_user_id_31e609_idx"
                    ),
                    models.Index(
                        fields=["is_completed"], name="user_profil_is_comp_bc65c5_idx"
                    ),
                ],
            },
        ),
    ]
