# Generated by Django 5.1.6 on 2025-02-17 21:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grade", "0003_alter_grade_options"),
        ("hard_skill", "0001_initial"),
        ("profession", "0003_alter_profession_options"),
        ("user_profile", "0001_initial"),
        ("work_format", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["user"], name="user_profil_user_id_31e609_idx"),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["is_completed"], name="user_profil_is_comp_bc65c5_idx"
            ),
        ),
    ]
