# Generated by Django 5.0.7 on 2024-08-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hard_skill", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hardskill",
            name="ordering",
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
    ]
