from apps.skill.utils import parse_skills

# fmt: off
_SKILL_GROUPS = {
    ".NET": (".net", ".net core", ".net framework"),
    "1С": ("1с", "1c", "1с программирование", "1c программирование", "1С программирование", "1C программирование",),
    "1С-Битрикс": ("1с-битрикс", "1c-битрикс"),
    "Azure": ("azure"),
    "Asyncio": ("asyncio",),
    "Confluence": ("atlassian confluence", "confluence"),
    "Jira": ("atlassian jira", "jira"),
    "Apache Airflow": ("apache airflow", "airflow"),
    "Apache Spark": ("apache spark", "spark"),
    "Ajax": ("ajax",),
    "API": ("api", "web api"),
    "Agile": ("agile",),
    "ASP.NET": ("asp net", "aspnet", "asp.net"),
    "Android": ("android",),
    "Angular": ("angular", "angular js", "angular.js"),
    "Ansible": ("ansible",),
    "Assembly": ("assembly",),
    "AWS": ("aws",),
    "BPMN": ("bpmn",),
    "Bash": ("bash",),
    "Babel": ("babel",),
    "Bootstrap": ("bootstrap",),
    "BitBucket": ("bitbucket",),
    "Битрикс24": ("битрикс", "битрикс24", "битрикс 24", "bitrix24", "bitrix 24"),
    "Cassandra": ("cassandra",),
    "CSS": ("css", "css3", "css 3"),
    "CRM": ("crm",),
    "SASS": ("scss", "sass"),
    "Sentry": ("sentry",),
    "Scrum": ("scrum",),
    "Symfony": ("symfony",),
    "Slack": ("slack",),
    "C": ("c",),
    "C#": ("c#",),
    "C++": ("c++",),
    "CI/CD": ("ci/cd",),
    "Celery": ("celery",),
    "ClickHouse": ("clickhouse",),
    "Cucumber": ("cucumber",),
    "DDD": ("ddd",),
    "DHCP": ("dhcp",),
    "DNS": ("dns", "настройка dns"),
    "Delphi": ("delphi",),
    "Linux": ("debian", "linux", "ubuntu", "unix"),
    "Dart": ("dart",),
    "DevOps": ("devops",),
    "Django": ("django",),
    "Django REST Framework": ("django rest", "django framework", "django rest framework", "rest framework",),
    "1С ERP": ("1с erp", "1c erp", "erp-системы на базе 1с", "1c: erp", "1с: erp", "1с:erp", "1c:erp", "1с-erp", "1с: erp управление предприятием",),
    "Excel": ("excel", "ms excel", "microsoft excel", "знание excel"),
    "Docker": ("docker", "docker compose", "docker-compose"),
    "Express": ("express", "express js", "express.js"),
    "Erlang": ("erlang",),
    "Ember.js": ("emberjs", "ember js", "ember.js"),
    "Electron": ("electron",),
    "Elasticsearch": ("elasticsearch", "elastic search", "elk"),
    "Elixir": ("elixir",),
    "F#": ("f#",),
    "FastAPI": ("fastapi", "fast api"),
    "Figma": ("figma",),
    "Flask": ("flask",),
    "Flutter": ("flutter",),
    "Gradle": ("gradle",),
    "Git": ("git",),
    "Grails": ("grails",),
    "gRPC": ("grpc",),
    "GitHub": ("github",),
    "GitLab": ("gitlab",),
    "GitLab CI": ("gitlab ci", "gitlabci", "gitlab ci/cd", "gitlab-ci"),
    "Go": ("go", "golang", "go lang"),
    "GraphQL": ("graphql",),
    "Grafana": ("grafana",),
    "Helm": ("helm",),
    "HTML": ("html", "html5", "html 5"),
    "Haskell": ("haskell",),
    "HTTP": ("http", "https"),
    "iOS": ("ios",),
    "JQuery": ("jquery",),
    "JavaScript": ("js", "javascript", "java script"),
    "JSON": ("json",),
    "Java": ("java",),
    "Jenkins": ("jenkins",),
    "Jest": ("jest",),
    "Apache Kafka": ("kafka", "apache kafka"),
    "Kanban": ("kanban",),
    "Kotlin": ("kotlin",),
    "Kubernetes": ("kubernetes", "k8s"),
    "Laravel": ("laravel",),
    "Lua": ("lua",),
    "Less": ("less",),
    "MacOS": ("macos",),
    "MariaDB": ("mariadb",),
    "MongoDB": ("mongodb",),
    "MobX": ("mobx",),
    "Meteor": ("meteor",),
    "Mercurial": ("mercurial",),
    "Microsoft Office": ("ms office", "mc office", "знание ms office", "знание программ ms office", "microsoft office", "ms-office", "office",),
    "MySQL": ("mysql",),
    "MS SQL": ("mssql", "ms sql"),
    "Nginx": ("nginx",),
    "Node.js": ("node.js", "nodejs", "node js"),
    "Next.js": ("nextjs", "next.js", "next js"),
    "Nuxt.js": ("nuxtjs", "nuxt", "nuxt.js", "nuxt js"),
    "NestJS": ("nestjs", "nest.js", "nest js"),
    "NoSQL": ("nosql", "no sql"),
    "ООП": ("oop", "ооп"),
    "Oracle": ("oracle", "oracle db"),
    "OpenShift": ("openshift",),
    "PHP": ("php",),
    "PostgreSQL": ("postgresql", "postgres", "postgre sql", "postgres sql", "postgresql sql", "psql",),
    "Python": ("python", "python3", "python 3"),
    "Pytest": ("pytest",),
    "PyTorch": ("pytorch",),
    "Prometheus": ("prometheus",),
    "Perl": ("perl",),
    "Pandas": ("pandas",),
    "Postman": ("postman",),
    "REST API": ("rest", "restapi", "rest api", "restful", "restful api", "rest-api"),
    "RabbitMQ": ("rabbit", "rabbit mq", "rabbitmq"),
    "React": ("react", "react.js", "react js"),
    "React Native": ("reactnative", "react native"),
    "Redis": ("redis",),
    "Redux": ("redux",),
    "Redux Toolkit": ("redux toolkit", "redux-toolkit"),
    "React Testing Library": ("react testing library",),
    "React Query": ("react-query", "react query"),
    "RTK Query": ("rtk-query", "rtk query"),
    "Ruby": ("ruby",),
    "Ruby on Rails": ("ruby on rails",),
    "Rust": ("rust",),
    "RxJS": ("rxjs",),
    "SOLID": ("solid",),
    "Svelte": ("svelte",),
    "Selenium": ("selenium",),
    "SEO": ("seo", "seo оптимизация", "seo-оптимизация"),
    "SQL": ("sql",),
    "SQLite": ("sqlite",),
    "SQLAlchemy": ("sqlalchemy", "sql alchemy"),
    "Spring Framework": ("spring", "spring framework"),
    "Spring Boot": ("spring boot",),
    "Swift": ("swift",),
    "Swagger": ("swagger",),
    "SOAP": ("soap",),
    "SOAP API": ("soap api",),
    "TCP/IP": ("tcp/ip",),
    "Tailwind": ("tailwind", "tailwindcss", "tailwind css"),
    "TypeScript": ("ts", "typescript", "type script"),
    "TensorFlow": ("tensorflow",),
    "Terraform": ("terraform",),
    "Unity": ("unity",),
    "UI/UX": ("ui", "ux", "ui/ux"),
    "UML": ("uml",),
    "Vite": ("vite",),
    "Vue": ("vue", "vue3", "vue js", "vuejs", "vue.js"),
    "Vuex": ("vuex",),
    "VMware": ("vmware", "vmware esxi", "vmware vsphere", "vmware vcenter"),
    "Webpack": ("webpack",),
    "Word": ("word", "ms word", "microsoft word", "знание word"),
    "WebSocket": ("websocket", "websockets"),
    "Windows": ("ос windows", "windows 10", "microsoft windows", "windows 7", "windows", "ms windows",),
    "Windows Server": ("windows server", "windows server 2019", "microsoft windows server", "ms windows server", "администрирование серверов windows",),
    "XHTML": ("xhtml",),
    "XML": ("xml",),
    "Yii": ("yii", "yii2"),
    "Zabbix": ("zabbix",),
    "Zustand": ("zustand",),
}
# fmt: on


IGNORE_SKILLS: tuple[str, ...] = (
    "функциональное тестирование",
    "ручное тестирование",
    "английский язык",
    "регрессионное тестирование",
    "автоматизированное тестирование",
    "тестирование пользовательского интерфейса",
    "кассовые чеки",
    "обслуживание покупателей",
    "кассовые операции",
    "мерчандайзинг",
    "тестирование",
    "приемка товара",
    "визуальный мерчандайзинг",
    "консультативные продажи",
    "ведение переговоров",
    "оформление торгового зала",
    "активные продажи",
    "системный анализ",
    "бизнес-анализ",
    "аналитическое мышление",
    "постановка задач разработчикам",
    "разработка технических заданий",
    "управление проектами",
    "выкладка товаров",
    "заказ товара",
)


SKILLS: tuple[str, ...] = tuple(map(lambda s: s.name, parse_skills(flat=True)))


# {
#    "react": "React",
#    "reactjs": "React",
#    "python": "Python",
# }
SKILL_MAPPING = {key: skill for skill, keys in _SKILL_GROUPS.items() for key in keys}
