from apps.skill.utils import parse_skills

# FIXME добавить на всякий проверку, что key.lower() not in values: raise exception
# fmt: off
_SKILL_GROUPS = {
    ".NET": (".net", ".net core", ".net framework"),
    "1С": ("1с", "1c", "1с программирование", "1c программирование", "1С программирование", "1C программирование",),
    "1С Битрикс": ("1с-битрикс", "1c-битрикс", "1с битрикс", "1С-Битрикс"),
    "1С Документооборот": ("1с: документооборот", "1с:документооборот",),
    "1С Зарплата и управление персоналом": ("1с: зарплата и управление персоналом", "1с:зарплата и управление персоналом",),
    "1С Управление торговлей": ("1с: управление торговлей", "1с:управление торговлей", "1с управление торговлей", "управление торговлей"),
    "1С Бухгалтерия": ("1с: бухгалтерия", "1c: бухгалтерия", "бухгалтерия", "1с бухгалтерия", "1с:бухгалтерия", "1с: бухгалтерия предприятия", "бухгалтерия государственного учреждения",),
    "1С Предприятие": ("1с: предприятие 8", "1с: управление производственным предприятием", "1с:предприятие", "1с: предприятие", "1с: предприятие 8.3", "1с: управление предприятием", "1с предприятие", "1с:erp управление предприятием", "1с:предприятие 8", "1c: предприятие", "	1c:предприятие 8.3", "1с:предприятие 8.3", "1с: предприятие: управление строительной организацией", "1c:предприятие", "1с:управление производственным предприятием"),
    "Azure": ("azure", "azure devops", "azure synapse", "azure ad", "azure ml", "azure cloud", "microsoft azure", "azure datalake",),
    "Asyncio": ("asyncio",),
    "Allure": ("allure",),
    "Apache": ("apache",),
    "Confluence": ("atlassian confluence", "confluence",),
    "Jira": ("atlassian jira", "jira",),
    "Apache Airflow": ("apache airflow", "airflow",),
    "Apache Spark": ("apache spark", "spark",),
    "Ajax": ("ajax",),
    "Asterisk": ("asterisk", "asterisknow", "ip-атс asterisk",),
    "Active Directory": ("active directory", "microsoft active directory", "ms active directory", "администрирование active directory"),
    "Ahrefs": ("ahrefs",),
    "API": ("api", "web api"),
    "Agile": ("agile",),
    "aiohttp": ("aiohttp",),
    "Android SDK": ("android sdk",),
    "ASP.NET": ("asp net", "aspnet", "asp.net", "asp.net core", "asp.net mvc"),
    "Android": ("android",),
    "Angular": ("angular", "angular js", "angular.js", "angularjs"),
    "Ansible": ("ansible",),
    "Assembly": ("assembly",),
    "AWS": ("aws", "aws s3", "aws sagemaker", "aws glue", "aws redshift"),
    "BPMN": ("bpmn",),
    "Bitrix": ("Битрикс24", "битрикс-24", "crm битрикс 24", "bitrix", "bitrix framework", "bitrix api", "crm bitrix", "bitrix crm", "cms bitrix", "api bitrix", "битрикс", "битрикс24", "битрикс 24", "bitrix24", "bitrix 24"),
    "BGP": ("bgp",),
    "Big Data": ("big data", "bigdata"),
    "Babel": ("babel",),
    "Bootstrap": ("bootstrap",),
    "BitBucket": ("bitbucket",),
    "Cassandra": ("cassandra",),
    "CSS": ("css", "css3", "css 3"),
    "CRM": ("crm",),
    "can": ("can",),
    "Cisco": ("cisco", "cisco ise", "cisco asa", "cisco firepower", "cisco security", "cisco wlc", "cisco mds", "cisco nexus", "cisco catalyst"),
    "SASS": ("scss", "sass"),
    "Sentry": ("sentry",),
    "Scrum": ("scrum",),
    "Symfony": ("symfony",),
    "Slack": ("slack",),
    "C": ("c",),
    "Cypress": ("cypress",),
    "CentOS": ("centos",),
    "C#": ("c#",),
    "C++": ("c++",),
    "CI/CD": ("ci/cd",),
    "Celery": ("celery",),
    "ClickHouse": ("clickhouse",),
    "Cucumber": ("cucumber",),
    "DDD": ("ddd",),
    "DHCP": ("dhcp",),
    "DNS": ("dns", "настройка dns"),
    "Delphi": ("delphi",),
    "Linux": ("bash", "debian", "linux", "ubuntu", "unix", "astra linux", "astralinux", "astra linux se", "ос astra linux", "администрирование astra linux", "astra", "centos",),
    "Dart": ("dart",),
    "DevOps": ("devops",),
    "Django": ("django", "django orm", "django rest", "django framework", "django rest framework", "rest framework",),
    "1С ERP": ("1с erp", "1c erp", "erp-системы на базе 1с", "1c: erp", "1с: erp", "1с:erp", "1c:erp", "1с-erp", "1с: erp управление предприятием",),
    "Excel": ("excel", "ms excel", "microsoft excel", "знание excel", "продвинутый пользователь excel", "навыки работы с excel", "макросы в excel", "работа с excel", "работа в excel"),
    "Docker": ("docker", "docker compose", "docker-compose"),
    "Express": ("express", "express js", "express.js"),
    "ETL": ("etl", "etl/elt",),
    "Exchange": ("exchange", "ms exchange", "microsoft exchange", "microsoft exchange server", "ms exchange server", "exchange online"),
    "Erlang": ("erlang",),
    "Ember.js": ("emberjs", "ember js", "ember.js",),
    "Electron": ("electron",),
    "Elasticsearch": ("elasticsearch", "elastic search", "elk"),
    "Elixir": ("elixir",),
    "Ethernet": ("ethernet", "ethernet apl",),
    "F#": ("f#",),
    "firebase": ("firebase",),
    "FastAPI": ("fastapi", "fast api"),
    "Figma": ("figma",),
    "Flask": ("flask",),
    "FTP": ("ftp",),
    "Flutter": ("flutter",),
    "Gradle": ("gradle",),
    "Google Search Console": ("google search console", "навыки работы с google search console"),
    "Google Analytics": ("google analytics", "навыки работы с google analytics", "google analytics"),
    "Greenplum": ("greenplum",),
    "Graylog": ("graylog", "graylog)",),
    "Git": ("git", "gitlab", "github",),
    "Grails": ("grails",),
    "gRPC": ("grpc",),
    "GitLab CI": ("gitlab ci", "gitlabci", "gitlab ci/cd", "gitlab-ci"),
    "Go": ("go", "golang", "go lang"),
    "GraphQL": ("graphql",),
    "Grafana": ("grafana", ""),
    "Helm": ("helm",),
    "NAT": ("nat",),
    "HTML": ("html", "html5", "html 5"),
    "Haskell": ("haskell",),
    "Hyper-V": ("hyper-v", "ms hyper-v"),
    "HTTP": ("http", "https", "http(s)", "http-сервисы", "http/api", "http/https", "http2", "http3", "http api"),
    "Hadoop": ("hadoop", "apache hadoop"),
    "iOS": ("ios",),
    "IIS": ("iis", "администрирование iis"),
    "IPsec": ("ipsec", "ipsec vpn", "ssl/ipsec vpn", "s2s ipsec vpn"),
    "JQuery": ("jquery",),
    "JavaScript": ("js", "javascript", "java script"),
    "JSON": ("json", "json api", "json schema", "json-ld"),
    "Java": ("java",),
    "Juniper": ("juniper",),
    "Jenkins": ("jenkins",),
    "Jest": ("jest",),
    "Apache Kafka": ("kafka", "apache kafka"),
    "Kanban": ("kanban",),
    "ML": ("ml", "mlflow", "mlops"),
    "Kotlin": ("kotlin",),
    "KVM": ("kvm",),
    "Kibana": ("kibana",),
    "Kubernetes": ("kubernetes", "k8s"),
    "Laravel": ("laravel",),
    "Lua": ("lua",),
    "Less": ("less",),
    "MacOS": ("macos",),
    "MVVM": ("mvvm",),
    "MariaDB": ("mariadb",),
    "MongoDB": ("mongodb",),
    "MobX": ("mobx",),
    "Meteor": ("meteor",),
    "Mercurial": ("mercurial",),
    "Mikrotik": ("mikrotik", "маршрутизаторы mikrotik"),
    "Microsoft Office": ("ms office", "mc office", "знание ms office", "знание программ ms office", "microsoft office", "ms-office", "office", "microsoft office 365", "office 365", "office 2016", "уверенный пользователь ms office", "msoffice"),
    "MS Project": ("ms project", "microsoft project", "microsoft projects"),
    "MySQL": ("mysql",),
    "Miro": ("miro",),
    "MS Visio": ("ms visio", "visio"),
    "MS SQL": ("mssql", "ms sql"),
    "Nginx": ("nginx", "angie/nginx"),
    "NGFW": ("ngfw",),
    "numpy": ("numpy",),
    "Notion": ("notion",),
    "Node.js": ("node.js", "nodejs", "node js",),
    "Next.js": ("nextjs", "next.js", "next js",),
    "Nuxt.js": ("nuxtjs", "nuxt", "nuxt.js", "nuxt js",),
    "NestJS": ("nestjs", "nest.js", "nest js",),
    "NoSQL": ("nosql", "no sql",),
    "ООП": ("oop", "ооп",),
    "OSI": ("osi",),
    "OSPF": ("ospf",),
    "Oracle": ("oracle", "oracle db",),
    "OpenShift": ("openshift",),
    "PHP": ("php",),
    "Playwright": ("playwright",),
    "Power Query": ("power query", "powerquery"),
    "Proxmox": ("proxmox",),
    "PostgreSQL": ("postgresql", "postgres", "postgre sql", "postgres sql", "postgresql sql", "psql",),
    "Python": ("python", "python3", "python 3"),
    "Pytest": ("pytest",),
    "Photoshop": ("adobe photoshop", "photoshop"),
    "PMBOK": ("pmbok",),
    "PyTorch": ("pytorch",),
    "Power BI": ("power bi", "powerbi", "bi (power bi)", "ms power bi"),
    "Prometheus": ("prometheus",),
    "Perl": ("perl",),
    "Pandas": ("pandas",),
    "Postman": ("postman",),
    "REST API": ("rest", "restapi", "rest api", "restful", "restful api", "rest-api"),
    "RabbitMQ": ("rabbit", "rabbit mq", "rabbitmq"),
    "RDP": ("rdp",),
    "React": ("react", "react.js", "react js"),
    "React Native": ("reactnative", "react native"),
    "Redis": ("redis",),
    "Redux": ("redux",),
    "Redux Toolkit": ("redux toolkit", "redux-toolkit"),
    "React Testing Library": ("react testing library",),
    "React Query": ("react-query", "react query"),
    "RTK Query": ("rtk-query", "rtk query"),
    "Ruby": ("ruby",),
    "Ruby on Rails": ("ruby on rails",),
    "Rust": ("rust",),
    "RxJS": ("rxjs",),
    "SOLID": ("solid",),
    "SIP": ("sip", "sip-телефония", "opensips", "sip trunk", "sip-телефонии", "sip телефония"),
    "Svelte": ("svelte",),
    "Scikit-learn": ("scikit-learn",),
    "SMTP": ("smtp",),
    "SNMP": ("snmp",),
    "SSH": ("ssh",),
    "Selenium": ("selenium", "selenium ide"),
    "SEO": ("seo", "seo оптимизация", "seo-оптимизация"),
    "SQL": ("sql",),
    "Screaming Frog": ("screaming frog",),
    "SQLite": ("sqlite",),
    "SQLAlchemy": ("sqlalchemy", "sql alchemy"),
    "Spring Framework": ("spring", "spring framework"),
    "Spring Boot": ("spring boot",),
    "Swift": ("swift",),
    "Swagger": ("swagger",),
    "SOAP": ("soap",),
    "SOAP API": ("soap api",),
    "TCP/IP": ("tcp/ip", "tcp", "tcpdump", "tcp-ip"),
    "Tailwind": ("tailwind", "tailwindcss", "tailwind css"),
    "TypeScript": ("ts", "typescript", "type script"),
    "TensorFlow": ("tensorflow",),
    "Trello": ("trello",),
    "UX/UI": ("ux/ui", "ux/ui-дизайн", "ux/ui дизайн",),
    "Terraform": ("terraform",),
    "TeamCity": ("teamcity",),
    "Tilda": ("tilda",),
    "Tableau": ("tableau",),
    "Unity": ("unity",),
    "UI/UX": ("ui", "ux", "ui/ux"),
    "UML": ("uml",),
    "UDP": ("udp",),
    "Veeam": ("veeam", "veeam backup", "veeam backup & replication", "veeam b&r"),
    "Vite": ("vite",),
    "VLAN": ("vlan",),
    "VPN": ("vpn", "openvpn", "l3 vpn", "l2 vpn", "l2vpn", "l3vpn"),
    "Vue": ("vue", "vue3", "vue js", "vuejs", "vue.js"),
    "Vuex": ("vuex",),
    "VMware": ("vmware", "vmware esxi", "vmware vsphere", "vmware vcenter"),
    "Webpack": ("webpack",),
    "WSUS": ("wsus",),
    "WordPress": ("wordpress", "cms wordpress"),
    "Word": ("word", "ms word", "microsoft word", "знание word"),
    "WebSocket": ("websocket", "websockets"),
    "Windows": ("ос windows", "windows 10", "microsoft windows", "windows 7", "windows", "ms windows", "powershell", "windows powershell",),
    "Windows Server": ("windows server", "windows server 2019", "microsoft windows server", "ms windows server", "администрирование серверов windows",),
    "XHTML": ("xhtml",),
    "XML": ("xml",),
    "Yii": ("yii", "yii2"),
    "Zabbix": ("zabbix",),
    "Zustand": ("zustand",),
    "Zabbix": ("zabbix", "zabbix-proxy"),
    "Яндекс.Метрика": ("яндекс.метрика",),
}
# fmt: on


IGNORE_SKILLS: tuple[str, ...] = (
    "функциональное тестирование",
    "ручное тестирование",
    "английский язык",
    "регрессионное тестирование",
    "автоматизированное тестирование",
    "тестирование пользовательского интерфейса",
    "кассовые чеки",
    "обслуживание покупателей",
    "кассовые операции",
    "мерчандайзинг",
    "тестирование",
    "приемка товара",
    "визуальный мерчандайзинг",
    "консультативные продажи",
    "ведение переговоров",
    "оформление торгового зала",
    "активные продажи",
    "системный анализ",
    "бизнес-анализ",
    "аналитическое мышление",
    "постановка задач разработчикам",
    "разработка технических заданий",
    "управление проектами",
    "выкладка товаров",
    "заказ товара",
)


SKILLS: tuple[str, ...] = tuple(map(lambda s: s.name, parse_skills(flat=True)))


# {
#    "react": "React",
#    "reactjs": "React",
#    "python": "Python",
# }
SKILL_MAPPING = {key: skill for skill, keys in _SKILL_GROUPS.items() for key in keys}
