# Generated by Django 5.1.6 on 2025-02-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0002_profile_user_profil_user_id_31e609_idx_and_more"),
        ("vacancy", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="profilevacancy",
            index=models.Index(
                fields=["profile"], name="vacancy_pro_profile_639ef9_idx"
            ),
        ),
    ]
