# Generated by Django 5.1.4 on 2025-01-04 15:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0001_initial"),
        ("vacancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileVacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_viewed", models.BooleanField(default=False)),
                (
                    "suitability",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancies",
                        to="user_profile.profile",
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vacancy.vacancy",
                    ),
                ),
            ],
            options={
                "unique_together": {("profile", "vacancy")},
            },
        ),
        migrations.DeleteModel(
            name="UserVacancy",
        ),
    ]
