# Generated by Django 5.1.4 on 2024-12-22 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hard_skill", "0004_alter_hardskill_ordering"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hardskill",
            options={},
        ),
    ]
